### ISSUE TITLE
webdriver.dll and admin rights

### ISSUE THREAD

**Issue by kimmolinna** [Dyalog/Selenium#2]
Webdriver is not working if you run Dyalog as administrator.

**Comment by mbaas2** [comment]
It does for me. Can you please provide additional details (i.e. the exact message you're getting etc.)?

**Comment by kimmolinna** [comment]
I think that the problem is then related to user account. I sign on my computer with my hotmail-account and I don't use local user.
If the browser is closed I will get the following error message: "Could not load WebDriver.dll and WebDriver.Support.dll from c:/devt/Selenium/Edge84/ ─ they may be blocked (Properties>General>Unblock) Or maybe something else is wrong. Here are the details of the exception: unknown error: unable to discover open window in chrome (Session info: MicrosoftEdge=84.0.522.52).
If the browser is open I will get the following error message: in Edge:  "Chrome automation extension is crached." and when I close the command prompt I will get the following error message in Dyalog: "Could not load WebDriver.dll and WebDriver.Support.dll from c:/devt/Selenium/Edge84/ ─ they may be blocked (Properties>General>Unblock)
Or maybe something else is wrong. Here are the details of the exception:
A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhos
t:65172/session. The status of the exception was ReceiveFailure, and the message was: Background application was closed.(translation from finnish - not accurate. :))

**Comment by mbaas2** [comment]
Duh - that seems to require some digging. Can u pls. me email me at mbaas@dyalog.com and then we'll continue the discussion by mail...

**Comment by mbaas2** [comment]
Issue is with the extension.
