### ISSUE TITLE
Hardcoded location of Newtonsoft.Json

### ISSUE THREAD

**Issue by kimmolinna** [Dyalog/Selenium#3]
Location of Newtonsoft.Json is hardcoded and you can't adjust it in settings.json.

**Comment by mbaas2** [comment]
I hope this addresses the issue sufficiently. Please let me know if it works out as expected...

**Comment by kimmolinna** [comment]
I got it work already earlier. My comment was just a comment. 😉

**Comment by mbaas2** [comment]
Yeah, but it was valid comment and it should have been done differently before. I think the current solution is better - but am not entirely happy with it...
